### PR TITLE
Small spelling fixes

### PR DESCRIPTION
**Pull request by barbatrucs**
Hi Wes,
Following my mail, I finally manage to send you these few small spelling fixes, if you're interested about.

### CODE REVIEW

**Comment by wesbos** [comment]
Hey thanks a ton - I actually write the talk in the 'index.jade' file and then run `gulp` to compile to html. - can you make the change in the .jade file?

**Comment by barbatrucs** [comment]
Hey, sure, I totally missed that, sorry. I will make the changes and recompile the files.

**Comment by barbatrucs** [comment]
I updated the jade template and recompiled the 'index.html' file.

**Comment by wesbos** [comment]
thanks a ton!

**Comment by barbatrucs** [comment]
You're really welcome. If you some small fixes in code or other, and no time to make the fix, I would be glad to do it for you, that's a good way to learn new things for me. See you

**Pull request merged**
